#!/bin/bash

DIR=`dirname $0`

if [ -f "bower.json" ]; then
  head -n 7 bower.json
fi
grunt-init $DIR --force

git checkout lib/*.js
git checkout test/*.js
git checkout example
git checkout HISTORY.md
git checkout README.md

npm install
bower install
